# Generated by Django 5.0.3 on 2024-04-04 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='docs',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
