# Generated by Django 5.0.3 on 2024-04-04 13:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='docs',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
